Import("env")
import os
import subprocess
import datetime

env.Replace(COMPILATIONDB_INCLUDE_TOOLCHAIN=True)
env.Replace(COMPILATIONDB_PATH=os.path.join("$BUILD_DIR", "../../compile_commands.json")) # in .pio/ directory

env.AddCustomTarget(
	"build",
	"$BUILD_DIR/${PROGNAME}.bin",
	print("build finished")
)

gitTag = subprocess.check_output(['git', 'describe', '--always', '--dirty', '--tags']).strip().decode('utf-8')

VERSION_CONTENTS = """// auto-generated by .extra_scripts.py
#include "version.h"
namespace version {{
	const char* const version = "{}-{}";
	const char* const env = "{}";
}}
""".format(gitTag, datetime.datetime.now().strftime("%H:%M:%S"), env.subst("$PIOENV"))

with open(os.path.join(env.subst("$PROJECT_SRC_DIR"), "./lib/version.cpp"), 'w+') as FILE:
	FILE.write(VERSION_CONTENTS)

print("wrote version.cpp")
